"""
Base embedding provider interfaces and data transfer objects.
Fulfills Prompt 8.1:
- Provider-independent abstract interface.
- Complete metadata tracking (model ID, version, dimension, normalization, timestamp, provider).
- Robust error handling, retries, timeouts, and batching.
"""

from __future__ import annotations

import asyncio
from abc import ABC, abstractmethod
from datetime import datetime, timezone
import math
from typing import Any

from pydantic import BaseModel, Field

from backend.app.models.chunk import EmbeddingModelType


class EmbeddingError(Exception):
    """Base exception for embedding pipeline errors."""
    pass


class EmbeddingDimensionMismatchError(EmbeddingError):
    """Raised when an embedding vector does not match the configured dimensions."""
    def __init__(self, expected: int, received: int, model_name: str):
        super().__init__(
            f"Embedding dimension mismatch for model '{model_name}': "
            f"expected {expected}, got {received}."
        )
        self.expected = expected
        self.received = received
        self.model_name = model_name


class EmbeddingProviderUnavailableError(EmbeddingError):
    """Raised when an embedding provider cannot be reached or initialized."""
    pass


class EmbeddingMetadata(BaseModel):
    """Metadata recorded for every generated vector embedding."""
    model_name: str
    model_version: str | None = None
    dimensions: int
    is_normalized: bool = True
    provider: str
    embedding_type: EmbeddingModelType = EmbeddingModelType.TEXT
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class EmbeddingResult(BaseModel):
    """Container for an individual generated embedding vector and its metadata."""
    vector: list[float]
    dimensions: int
    norm: float
    metadata: EmbeddingMetadata
    tokens_used: int | None = None


class BatchEmbeddingResult(BaseModel):
    """Container for a batch of generated embedding vectors with failure tracking."""
    results: list[EmbeddingResult] = Field(default_factory=list)
    failed_indices: list[int] = Field(default_factory=list)
    errors: dict[int, str] = Field(default_factory=dict)

    @property
    def success_count(self) -> int:
        return len(self.results)

    @property
    def failure_count(self) -> int:
        return len(self.failed_indices)


def l2_normalize(vector: list[float]) -> tuple[list[float], float]:
    """Compute L2 norm, normalize vector to unit length, and return (normalized_vector, 1.0)."""
    norm = math.sqrt(sum(x * x for x in vector))
    if norm == 0.0:
        return vector, 0.0
    normalized = [x / norm for x in vector]
    return normalized, 1.0


class BaseEmbeddingProvider(ABC):
    """
    Abstract embedding provider interface.
    The application interacting with BaseEmbeddingProvider never relies on
    provider-specific implementation details.
    """

    def __init__(
        self,
        model_name: str,
        dimensions: int,
        provider_name: str,
        embedding_type: EmbeddingModelType = EmbeddingModelType.TEXT,
        model_version: str | None = None,
        is_normalized: bool = True,
        batch_size: int = 100,
        timeout: int = 30,
        retries: int = 3,
    ) -> None:
        self.model_name = model_name
        self.dimensions = dimensions
        self.provider_name = provider_name
        self.embedding_type = embedding_type
        self.model_version = model_version
        self.is_normalized = is_normalized
        self.batch_size = batch_size
        self.timeout = timeout
        self.retries = retries

    def get_metadata(self) -> EmbeddingMetadata:
        """Create standard metadata instance for embeddings generated by this provider."""
        return EmbeddingMetadata(
            model_name=self.model_name,
            model_version=self.model_version,
            dimensions=self.dimensions,
            is_normalized=self.is_normalized,
            provider=self.provider_name,
            embedding_type=self.embedding_type,
        )

    def validate_vector(self, vector: list[float]) -> tuple[list[float], float]:
        """
        Validate vector dimension and compute/apply normalization.
        Raises EmbeddingDimensionMismatchError if vector length does not match self.dimensions.
        """
        if len(vector) != self.dimensions:
            raise EmbeddingDimensionMismatchError(
                expected=self.dimensions,
                received=len(vector),
                model_name=self.model_name,
            )
        if self.is_normalized:
            norm_vec, norm = l2_normalize(vector)
            return norm_vec, norm
        norm = math.sqrt(sum(x * x for x in vector))
        return vector, norm

    @abstractmethod
    async def embed_batch(self, texts: list[str]) -> BatchEmbeddingResult:
        """Asynchronously compute embeddings for a batch of texts."""
        pass

    async def embed_single(self, text: str) -> EmbeddingResult:
        """Asynchronously compute embedding for a single text."""
        batch_res = await self.embed_batch([text])
        if batch_res.results:
            return batch_res.results[0]
        err_msg = batch_res.errors.get(0, "Failed to generate embedding")
        raise EmbeddingError(err_msg)

    def embed_batch_sync(self, texts: list[str]) -> BatchEmbeddingResult:
        """Synchronously compute embeddings for a batch of texts."""
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            import nest_asyncio  # type: ignore[import-untyped]
            nest_asyncio.apply()
            return loop.run_until_complete(self.embed_batch(texts))
        return asyncio.run(self.embed_batch(texts))

    def embed_single_sync(self, text: str) -> EmbeddingResult:
        """Synchronously compute embedding for a single text."""
        res = self.embed_batch_sync([text])
        if res.results:
            return res.results[0]
        err = res.errors.get(0, "Failed to generate embedding")
        raise EmbeddingError(err)
