"""
ChemRAG — Safety & Compliance Data Models
===========================================
Fulfills Phase 12 / Prompt 12.1 & Prompt 12.2:
- Explicit policy decisions: ALLOW, ALLOW_WITH_WARNING, REQUIRE_REVIEW, REFUSE.
- Authoritative risk categories (CWC schedules, explosive precursors, dual-use).
- Structured screening and policy evaluation result objects.
"""
from __future__ import annotations

from datetime import datetime, timezone
import enum
from typing import Any, Optional
import uuid

from pydantic import BaseModel, Field


class PolicyDecision(str, enum.Enum):
    """Core safety policy decision outcomes (Prompt 12.1)."""
    ALLOW = "ALLOW"
    ALLOW_WITH_WARNING = "ALLOW_WITH_WARNING"
    REQUIRE_REVIEW = "REQUIRE_REVIEW"
    REFUSE = "REFUSE"


class SafetyRiskCategory(str, enum.Enum):
    """Categorization of chemical and compliance risks."""
    CWC_SCHEDULE_1 = "cwc_schedule_1"          # Chemical weapons (e.g., Sarin, VX, Soman, Mustard)
    CWC_SCHEDULE_2 = "cwc_schedule_2"          # Key toxic chemicals / dual-use precursors
    CWC_SCHEDULE_3 = "cwc_schedule_3"          # Dual-use industrial chemicals produced in large quantities
    EXPLOSIVE_PRECURSOR = "explosive_precursor" # High explosives / energetic materials (e.g. TATP, RDX, PETN)
    ILLICIT_DRUG_PRECURSOR = "illicit_drug_precursor"  # Controlled narcotics & clandestine synthesis precursors
    LETHAL_TOXIN = "lethal_toxin"               # Biological/chemical biological toxins (e.g. Ricin, Saxitoxin)
    AUTONOMOUS_EXECUTION = "autonomous_execution" # Unauthorized robotic / automated synthesis control
    PROMPT_INJECTION = "prompt_injection"       # Adversarial system prompt override attempts
    MALICIOUS_DOCUMENT = "malicious_document"   # Indirect document injection


class UserRole(str, enum.Enum):
    """Role-based access control levels for chemistry operations."""
    GUEST = "guest"
    STUDENT = "student"
    RESEARCHER = "researcher"
    COMPLIANCE_OFFICER = "compliance_officer"
    ADMIN = "admin"


class RestrictedChemicalEntry(BaseModel):
    """Authoritative restricted chemical database record."""
    chemical_id: str
    primary_name: str
    cas_number: Optional[str] = None
    inchi_key: Optional[str] = None
    canonical_smiles: Optional[str] = None
    molecular_formula: Optional[str] = None
    synonyms: list[str] = Field(default_factory=list)
    risk_category: SafetyRiskCategory
    hazard_description: str
    regulatory_framework: str  # e.g., "CWC Schedule 1.A.01", "GDSL List 2"
    allowed_roles: list[UserRole] = Field(default_factory=lambda: [UserRole.COMPLIANCE_OFFICER, UserRole.ADMIN])


class ScreeningMatch(BaseModel):
    """Outcome of chemical entity screening against authoritative registries."""
    chemical_id: str
    matched_name: str
    matched_by: str  # "cas_number" | "inchi_key" | "canonical_smiles" | "synonym"
    risk_category: SafetyRiskCategory
    hazard_description: str
    regulatory_framework: str
    confidence: float = 1.0


class PolicyRule(BaseModel):
    """Configurable safety rule definition (stored in JSON or DB)."""
    rule_id: str
    name: str
    description: str
    action_pattern: str  # e.g., "synthesis", "property_lookup", "all"
    risk_categories: list[SafetyRiskCategory] = Field(default_factory=list)
    minimum_role: UserRole = UserRole.RESEARCHER
    default_decision: PolicyDecision = PolicyDecision.REFUSE
    warning_message: Optional[str] = None
    policy_version: str = "1.0.0"
    is_active: bool = True


class SafetyEvaluationResult(BaseModel):
    """
    Comprehensive safety verdict generated by the Policy Engine.
    Fully audited for regulatory compliance and institutional audit trails.
    """
    decision: PolicyDecision
    reason: str
    matched_rules: list[str] = Field(default_factory=list)
    matches: list[ScreeningMatch] = Field(default_factory=list)
    hazard_flags: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    user_role: UserRole = UserRole.RESEARCHER
    requested_action: str = "query"
    policy_version: str = "1.0.0"
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    @property
    def is_allowed(self) -> bool:
        return self.decision in (PolicyDecision.ALLOW, PolicyDecision.ALLOW_WITH_WARNING)


class SafetyViolationError(Exception):
    """Non-bypassable exception raised when a tool call violates safety policy."""

    def __init__(self, evaluation: SafetyEvaluationResult) -> None:
        self.evaluation = evaluation
        super().__init__(
            f"[ChemRAG Safety Violation] Action '{evaluation.requested_action}' REFUSED. "
            f"Reason: {evaluation.reason} (Matched Rules: {', '.join(evaluation.matched_rules)})"
        )
